//jai sri ram
export const EditorConfig = {
      value: "//open folder or\n \n  //open file or\n \n //write code now ",
      language: "javascript",
      automaticLayout: true,
      lineNumbers: "on",
      folding: true,
      minimap: { enabled: true },
      wordWrap: "off",
      codeLens: true,
      dragAndDrop: true,
      cursorBlinking: "blink",
      cursorStyle: "line",
      selectOnLineNumbers: true,
      quickSuggestions: true,
      snippetSuggestions: "inline",
      fontFamily: "JetBrains Mono",
      fontLigatures: true,
      fontWeight: 200,
      scrollbar: {
        horizontal: "visible",
        horizontalScrollbarSize: 12,
        alwaysConsumeMouseWheel: false,
        vertical: "visible",
      },
      theme: "NofericIDETheme",
      alwaysConsumeMouseWheel: false,
      suggest: {
        showMethods: true,
        showWords: true,
        showModules: true,
        showPaths: true,
        maxVisibleSuggestions: 12,
        shareSuggestSelections: true,
      },
    }